# Generated by Django 5.2.8 on 2025-12-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=2048)),
                ('last_name', models.CharField(max_length=2048)),
                ('email', models.EmailField(max_length=254)),
                ('type', models.CharField(choices=[('inquiry', 'استفسار'), ('suggestion', 'اقتراح'), ('help', 'طلب مساعدة'), ('complaint', 'شكوى')], default='inquiry', max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
