# Generated by Django 5.2.8 on 2025-12-01 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='rating',
        ),
    ]
