# Generated by Django 5.2.8 on 2025-12-01 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0002_remove_gym_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='name',
        ),
        migrations.AddField(
            model_name='gym',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gym', to=settings.AUTH_USER_MODEL),
        ),
    ]
