# Generated by Django 5.2.8 on 2025-12-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0004_rename_hood_gym_hoods_gymcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='name',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
