# Generated by Django 5.2.8 on 2025-12-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0005_gym_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='image',
            field=models.ImageField(default='avatars/default.png', upload_to='images/'),
        ),
    ]
