# Generated by Django 5.2.8 on 2025-12-03 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0006_alter_gym_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='gyms.gymcomment'),
        ),
        migrations.AlterField(
            model_name='gymcomment',
            name='rating',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
