# Generated by Django 5.2.8 on 2025-12-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0007_gymcomment_parent_alter_gymcomment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymcomment',
            name='comment_type',
            field=models.CharField(blank=True, choices=[('member', 'مشترك'), ('visitor', 'زائر'), ('question', 'استفسار')], max_length=20, null=True),
        ),
    ]
