# Generated by Django 5.2.8 on 2025-12-03 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0008_alter_gymcomment_comment_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gymcomment',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentioned_in_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gymcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
