# Generated by Django 5.2.8 on 2025-12-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0009_gymcomment_reply_to_alter_gymcomment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, default=600, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gym',
            name='website',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
