# Generated by Django 5.2.8 on 2025-12-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='avatar',
            field=models.ImageField(default='avatars/default.png', upload_to='images/'),
        ),
    ]
