# Generated by Django 5.2.8 on 2025-12-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_trainee_avatar'),
        ('coaches', '0008_remove_coach_price_subscriptionplan_usersubscription'),
        ('gyms', '0009_gymcomment_reply_to_alter_gymcomment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='favorite_coaches',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='coaches.coach'),
        ),
        migrations.AddField(
            model_name='trainee',
            name='favorite_gyms',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='gyms.gym'),
        ),
    ]
