# Generated by Django 5.2.8 on 2025-12-01 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='name',
        ),
    ]
