# Generated by Django 5.2.8 on 2025-12-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0002_remove_coach_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='avatar',
            field=models.ImageField(default='avatars/default.png', upload_to='images/'),
        ),
    ]
