# Generated by Django 5.2.8 on 2025-12-01 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0004_coachcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coachcomment',
            old_name='Coach',
            new_name='coach',
        ),
    ]
