# Generated by Django 5.2.8 on 2025-12-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0005_rename_coach_coachcomment_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachcomment',
            name='rating',
            field=models.SmallIntegerField(choices=[(1, 'One Star'), (2, 'Two Stars'), (3, 'Three Stars'), (4, 'Four Stars'), (5, 'Five Stars')], default=5),
        ),
        migrations.AddField(
            model_name='coachcomment',
            name='type',
            field=models.CharField(choices=[('inquiry', 'استفسار'), ('previous_member', 'مشترك سابق')], default='inquiry', max_length=20),
        ),
    ]
