# Generated by Django 5.2.8 on 2025-12-05 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_trainee_favorite_coaches_trainee_favorite_gyms'),
        ('coaches', '0008_remove_coach_price_subscriptionplan_usersubscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='user',
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='trainee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.trainee'),
            preserve_default=False,
        ),
    ]
