# Generated by Django 5.2.8 on 2025-12-06 22:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0011_alter_coach_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='رقم الجوال غير صحيح (مثال: 05xxxxxxxx)', regex='^(05|9665|\\+9665)\\d{8}$')], verbose_name='رقم الجوال'),
        ),
    ]
